export const REQUEST_PHOTOS_BY_ID = 'REQUEST_PHOTOS_BY_ID';
export const SUCCESS_REQUEST_PHOTOS_BY_ID = 'SUCCESS_REQUEST_PHOTOS_BY_ID';
export const FAILED_REQUEST_PHOTOS_BY_ID = 'FAILED_REQUEST_PHOTOS_BY_ID';

export const REQUEST_USERS = 'REQUEST_USERS';
export const SUCCESS_REQUEST_USERS = 'SUCCESS_REQUEST_USERS';
export const FAILED_REQUEST_USERS = 'FAILED_REQUEST_USERS';

export const REQUEST_PHOTOS = 'REQUEST_PHOTOS';
export const SUCCESS_REQUEST_PHOTOS = 'SUCCESS_REQUEST_PHOTOS';
export const FAILED_REQUEST_PHOTOS = 'FAILED_REQUEST_PHOTOS';

export const REQUEST_ALBUMS_BY_ID = 'REQUEST_ALBUMS_BY_ID';
export const SUCCESS_REQUEST_ALBUMS_BY_ID = 'SUCCESS_REQUEST_ALBUMS_BY_ID';
export const FAILED_REQUEST_ALBUMS_BY_ID = 'FAILED_REQUEST_ALBUMS_BY_ID';